# Generated by Django 5.0.6 on 2024-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0002_propertysearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysearch',
            name='max_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='min_price',
            field=models.IntegerField(),
        ),
    ]
