# Generated by Django 5.0.6 on 2024-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0003_alter_propertysearch_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
    ]
