# Generated by Django 5.0.6 on 2024-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0004_property_amenities_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
