# Generated by Django 5.0.6 on 2024-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0005_alter_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearch',
            name='amenities',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
