# Generated by Django 5.0.6 on 2024-06-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0006_propertysearch_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysearch',
            name='amenities',
        ),
    ]
