# Generated by Django 5.0.6 on 2024-06-18 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_recommender', '0007_remove_propertysearch_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysearch',
            name='search_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
